import { Html, Head, Main, NextScript } from 'next/document';

export default function Document() {
  return (
      <Html lang="en">
            <Head>
                    {/* Google Analytics GA4 */}
                            <script async src="https://www.googletagmanager.com/gtag/js?id=G-S6EMS4TTNP" />
                                    <script
                                              dangerouslySetInnerHTML={{
                                                          __html: `
                                                                        window.dataLayer = window.dataLayer || [];
                                                                                      function gtag(){dataLayer.push(arguments);}
                                                                                                    gtag('js', new Date());
                                                                                                                  gtag('config', 'G-S6EMS4TTNP', {
                                                                                                                                  page_path: window.location.pathname,
                                                                                                                                                });
                                                                                                                                                            `,
                                                                                                                                                                      }}
                                                                                                                                                                              />

                                                                                                                                                                                      {/* Google Search Console Verification */}
                                                                                                                                                                                              <meta name="google-site-verification" content="0567f50cc6b6dd62" />

                                                                                                                                                                                                      {/* Primary SEO */}
                                                                                                                                                                                                              <meta name="description" content="CrossLedger streamlines cross-border commodity settlement with smart escrow and on-chain verification. Stage 1 presale live at $0.10 CLXT. Built by GDN Group." />
                                                                                                                                                                                                                      <meta name="keywords" content="CrossLedger, CLXT, blockchain trade finance, commodity settlement, cross-border payments, presale, smart escrow, on-chain verification, GDN Group" />
                                                                                                                                                                                                                              <meta name="robots" content="index, follow" />
                                                                                                                                                                                                                                      <link rel="canonical" href="https://www.crossledger.trade/" />

                                                                                                                                                                                                                                              {/* Open Graph */}
                                                                                                                                                                                                                                                      <meta property="og:title" content="CrossLedger – Institutional-Grade Blockchain Trade Finance" />
                                                                                                                                                                                                                                                              <meta property="og:description" content="Smart escrow. On-chain document verification. Fast settlement. Join the Stage 1 presale at $0.10 per CLXT before allocation closes." />
                                                                                                                                                                                                                                                                      <meta property="og:type" content="website" />
                                                                                                                                                                                                                                                                              <meta property="og:url" content="https://www.crossledger.trade/" />
                                                                                                                                                                                                                                                                                      <meta property="og:image" content="https://www.crossledger.trade/api/og" />
                                                                                                                                                                                                                                                                                              <meta property="og:image:width" content="1200" />
                                                                                                                                                                                                                                                                                                      <meta property="og:image:height" content="630" />
                                                                                                                                                                                                                                                                                                              <meta property="og:image:type" content="image/svg+xml" />
                                                                                                                                                                                                                                                                                                                      <meta property="og:site_name" content="CrossLedger" />

                                                                                                                                                                                                                                                                                                                              {/* Twitter Card */}
                                                                                                                                                                                                                                                                                                                                      <meta name="twitter:card" content="summary_large_image" />
                                                                                                                                                                                                                                                                                                                                              <meta name="twitter:title" content="CLXT Presale Live | CrossLedger Trade Finance Platform" />
                                                                                                                                                                                                                                                                                                                                                      <meta name="twitter:description" content="Blockchain-anchored settlement for mid-market commodity exporters. Stage 1 at $0.10 – price increases at Stage 2." />
                                                                                                                                                                                                                                                                                                                                                              <meta name="twitter:image" content="https://www.crossledger.trade/api/og" />

                                                                                                                                                                                                                                                                                                                                                                      {/* Structured Data — WebSite */}
                                                                                                                                                                                                                                                                                                                                                                              <script
                                                                                                                                                                                                                                                                                                                                                                                        type="application/ld+json"
                                                                                                                                                                                                                                                                                                                                                                                                  dangerouslySetInnerHTML={{
                                                                                                                                                                                                                                                                                                                                                                                                              __html: JSON.stringify({
                                                                                                                                                                                                                                                                                                                                                                                                                            "@context": "https://schema.org",
                                                                                                                                                                                                                                                                                                                                                                                                                                          "@type": "WebSite",
                                                                                                                                                                                                                                                                                                                                                                                                                                                        "name": "CrossLedger",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      "url": "https://www.crossledger.trade",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    "description": "Institutional-grade blockchain settlement infrastructure for cross-border commodity trade.",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                })
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {/* Structured Data — Organization */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <script
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            type="application/ld+json"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      dangerouslySetInnerHTML={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  __html: JSON.stringify({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "@context": "https://schema.org",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              "@type": "Organization",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "name": "CrossLedger / GDN Group",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          "url": "https://www.crossledger.trade",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "logo": "https://www.crossledger.trade/favicon.ico",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      "description": "CrossLedger provides blockchain-powered settlement infrastructure for global commodity trade.",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    "sameAs": []
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                })
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {/* Fonts & Icons */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <link rel="icon" href="/favicon.ico" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <link rel="preconnect" href="https://fonts.googleapis.com" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </Head>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <body>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <Main />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <NextScript />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </body>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </Html>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }