import { useState, useEffect } from 'react';

// Stage 2 launch date — update this when Stage 2 date is confirmed
const STAGE2_DATE = new Date('2026-07-01T00:00:00Z');

function pad(n) {
  return String(n).padStart(2, '0');
  }

  export default function CountdownTimer() {
    const [timeLeft, setTimeLeft] = useState(null);
      const [expired, setExpired] = useState(false);

        useEffect(() => {
            function calculate() {
                  const now = new Date();
                        const diff = STAGE2_DATE - now;

                              if (diff <= 0) {
                                      setExpired(true);
                                              return;
                                                    }

                                                          const days = Math.floor(diff / (1000 * 60 * 60 * 24));
                                                                const hours = Math.floor((diff % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60));
                                                                      const minutes = Math.floor((diff % (1000 * 60 * 60)) / (1000 * 60));
                                                                            const seconds = Math.floor((diff % (1000 * 60)) / 1000);

                                                                                  setTimeLeft({ days, hours, minutes, seconds });
                                                                                      }

                                                                                          calculate();
                                                                                              const interval = setInterval(calculate, 1000);
                                                                                                  return () => clearInterval(interval);
                                                                                                    }, []);

                                                                                                      if (expired) {
                                                                                                          return (
                                                                                                                <div style={styles.wrapper}>
                                                                                                                        <p style={styles.expiredText}>Stage 2 is now live. Price has increased to $0.20.</p>
                                                                                                                              </div>
                                                                                                                                  );
                                                                                                                                    }

                                                                                                                                      if (!timeLeft) return null;

                                                                                                                                        return (
                                                                                                                                            <div style={styles.wrapper}>
                                                                                                                                                  <p style={styles.label}>⏳ Stage 1 price locks in</p>
                                                                                                                                                        <div style={styles.timerRow}>
                                                                                                                                                                <Segment value={timeLeft.days} unit="Days" />
                                                                                                                                                                        <Divider />
                                                                                                                                                                                <Segment value={timeLeft.hours} unit="Hours" />
                                                                                                                                                                                        <Divider />
                                                                                                                                                                                                <Segment value={timeLeft.minutes} unit="Min" />
                                                                                                                                                                                                        <Divider />
                                                                                                                                                                                                                <Segment value={timeLeft.seconds} unit="Sec" />
                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                            <p style={styles.sublabel}>Stage 2 price: <strong>$0.20 / CLXT</strong> — double the current rate</p>
                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                  );
                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                  function Segment({ value, unit }) {
                                                                                                                                                                                                                                    return (
                                                                                                                                                                                                                                        <div style={styles.segment}>
                                                                                                                                                                                                                                              <span style={styles.number}>{pad(value)}</span>
                                                                                                                                                                                                                                                    <span style={styles.unit}>{unit}</span>
                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                          );
                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                          function Divider() {
                                                                                                                                                                                                                                                            return <span style={styles.divider}>:</span>;
                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                            const styles = {
                                                                                                                                                                                                                                                              wrapper: {
                                                                                                                                                                                                                                                                  background: 'rgba(0, 0, 0, 0.35)',
                                                                                                                                                                                                                                                                      border: '1px solid rgba(255,255,255,0.12)',
                                                                                                                                                                                                                                                                          borderRadius: '12px',
                                                                                                                                                                                                                                                                              padding: '16px 24px',
                                                                                                                                                                                                                                                                                  textAlign: 'center',
                                                                                                                                                                                                                                                                                      marginTop: '20px',
                                                                                                                                                                                                                                                                                          marginBottom: '8px',
                                                                                                                                                                                                                                                                                              backdropFilter: 'blur(8px)',
                                                                                                                                                                                                                                                                                                },
                                                                                                                                                                                                                                                                                                  label: {
                                                                                                                                                                                                                                                                                                      color: '#a0aec0',
                                                                                                                                                                                                                                                                                                          fontSize: '13px',
                                                                                                                                                                                                                                                                                                              fontWeight: '500',
                                                                                                                                                                                                                                                                                                                  letterSpacing: '0.05em',
                                                                                                                                                                                                                                                                                                                      textTransform: 'uppercase',
                                                                                                                                                                                                                                                                                                                          margin: '0 0 10px 0',
                                                                                                                                                                                                                                                                                                                            },
                                                                                                                                                                                                                                                                                                                              timerRow: {
                                                                                                                                                                                                                                                                                                                                  display: 'flex',
                                                                                                                                                                                                                                                                                                                                      alignItems: 'center',
                                                                                                                                                                                                                                                                                                                                          justifyContent: 'center',
                                                                                                                                                                                                                                                                                                                                              gap: '4px',
                                                                                                                                                                                                                                                                                                                                                },
                                                                                                                                                                                                                                                                                                                                                  segment: {
                                                                                                                                                                                                                                                                                                                                                      display: 'flex',
                                                                                                                                                                                                                                                                                                                                                          flexDirection: 'column',
                                                                                                                                                                                                                                                                                                                                                              alignItems: 'center',
                                                                                                                                                                                                                                                                                                                                                                  minWidth: '56px',
                                                                                                                                                                                                                                                                                                                                                                    },
                                                                                                                                                                                                                                                                                                                                                                      number: {
                                                                                                                                                                                                                                                                                                                                                                          fontSize: '32px',
                                                                                                                                                                                                                                                                                                                                                                              fontWeight: '700',
                                                                                                                                                                                                                                                                                                                                                                                  color: '#ffffff',
                                                                                                                                                                                                                                                                                                                                                                                      fontVariantNumeric: 'tabular-nums',
                                                                                                                                                                                                                                                                                                                                                                                          lineHeight: '1',
                                                                                                                                                                                                                                                                                                                                                                                            },
                                                                                                                                                                                                                                                                                                                                                                                              unit: {
                                                                                                                                                                                                                                                                                                                                                                                                  fontSize: '10px',
                                                                                                                                                                                                                                                                                                                                                                                                      color: '#718096',
                                                                                                                                                                                                                                                                                                                                                                                                          letterSpacing: '0.08em',
                                                                                                                                                                                                                                                                                                                                                                                                              textTransform: 'uppercase',
                                                                                                                                                                                                                                                                                                                                                                                                                  marginTop: '4px',
                                                                                                                                                                                                                                                                                                                                                                                                                    },
                                                                                                                                                                                                                                                                                                                                                                                                                      divider: {
                                                                                                                                                                                                                                                                                                                                                                                                                          fontSize: '28px',
                                                                                                                                                                                                                                                                                                                                                                                                                              fontWeight: '700',
                                                                                                                                                                                                                                                                                                                                                                                                                                  color: '#4a5568',
                                                                                                                                                                                                                                                                                                                                                                                                                                      paddingBottom: '8px',
                                                                                                                                                                                                                                                                                                                                                                                                                                        },
                                                                                                                                                                                                                                                                                                                                                                                                                                          sublabel: {
                                                                                                                                                                                                                                                                                                                                                                                                                                              color: '#718096',
                                                                                                                                                                                                                                                                                                                                                                                                                                                  fontSize: '12px',
                                                                                                                                                                                                                                                                                                                                                                                                                                                      margin: '10px 0 0 0',
                                                                                                                                                                                                                                                                                                                                                                                                                                                        },
                                                                                                                                                                                                                                                                                                                                                                                                                                                          expiredText: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                              color: '#e53e3e',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  fontWeight: '600',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      fontSize: '14px',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          margin: 0,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            };